#!/usr/bin/env python3
"""
apply-hsaqmaodv-module.py
─────────────────────────────────────────────────────────────────────────────
Step 1 of H-SAQMAODV NS-3 integration.

Creates the NS-3 module directory:
  $NS3_DIR/src/hsaqmaodv/

Copies the H-SAQMAODV source files and wires up the CMakeLists.txt so
NS-3 can build `libhsaqmaodv`.

The module reuses ALL saqmaodv source files except for the Q-table,
which is replaced by hsaqmaodv-qtable.{h,cc}.

Usage:
    NS3_DIR=/path/to/ns-3.40 python3 apply-hsaqmaodv-module.py
"""

import os, sys, shutil, subprocess
from pathlib import Path

NS3_DIR  = Path(os.environ.get('NS3_DIR', Path.home() / 'ns-allinone-3.40/ns-3.40'))
PROJ_DIR = Path(__file__).resolve().parents[3]   # saqmaodv-ns3/

SRC_SA  = NS3_DIR / 'src' / 'saqmaodv'
DST_HS  = NS3_DIR / 'src' / 'hsaqmaodv'
FILES_DIR = PROJ_DIR / 'paper1-hsaqmaodv' / 'files'

def die(msg):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)

def info(msg):
    print(f"  [hsaqmaodv-module] {msg}")

# ─── Sanity checks ───────────────────────────────────────────────────────────
if not NS3_DIR.exists():
    die(f"NS3_DIR not found: {NS3_DIR}")
if not SRC_SA.exists():
    die(f"saqmaodv module not found at {SRC_SA}\n"
        f"  → Run the base SA-QMAODV patches first.")
if not (FILES_DIR / 'hsaqmaodv-qtable.h').exists():
    die(f"hsaqmaodv-qtable.h not found at {FILES_DIR}")

# ─── Create module directory tree ───────────────────────────────────────────
info(f"Creating {DST_HS}")
for sub in ['model', 'helper']:
    (DST_HS / sub).mkdir(parents=True, exist_ok=True)
(DST_HS / 'doc').mkdir(exist_ok=True)

# ─── Copy shared SA-QMAODV files (everything except q-table) ────────────────
SA_SHARED = [
    'model/saqmaodv-rtable.h',
    'model/saqmaodv-rtable.cc',
    'model/saqmaodv-rqueue.h',
    'model/saqmaodv-rqueue.cc',
    'model/saqmaodv-packet.h',
    'model/saqmaodv-packet.cc',
    'model/saqmaodv-routing-protocol.h',
    'model/saqmaodv-routing-protocol.cc',
    'helper/saqmaodv-helper.h',
    'helper/saqmaodv-helper.cc',
]

copied = []
for rel in SA_SHARED:
    src = SRC_SA / rel
    if src.exists():
        dst = DST_HS / rel
        # Rename saqmaodv_ → hsaqmaodv_ in filenames
        new_name = dst.name.replace('saqmaodv', 'hsaqmaodv')
        dst = dst.parent / new_name
        shutil.copy2(src, dst)
        copied.append(str(dst.relative_to(NS3_DIR)))
        info(f"  copied  {rel} → {dst.name}")

# ─── Copy H-SAQMAODV Q-table ─────────────────────────────────────────────────
for fname in ['hsaqmaodv-qtable.h', 'hsaqmaodv-qtable.cc']:
    src = FILES_DIR / fname
    dst = DST_HS / 'model' / fname
    shutil.copy2(src, dst)
    info(f"  copied  {fname}")

# ─── Patch namespace and includes in copied files ────────────────────────────
import re

def patch_file(path: Path):
    text = path.read_text(encoding='utf-8')
    # Rename namespace
    text = text.replace('namespace saqmaodv', 'namespace hsaqmaodv')
    text = text.replace('ns3::saqmaodv::', 'ns3::hsaqmaodv::')
    # Rename include guards and includes
    text = text.replace('SAQMAODV_', 'HSAQMAODV_')
    text = re.sub(r'#include "saqmaodv-qtable\.h"',
                  '#include "hsaqmaodv-qtable.h"', text)
    text = re.sub(r'#include "saqmaodv-', '#include "hsaqmaodv-', text)
    path.write_text(text, encoding='utf-8')

info("Patching namespace in copied files...")
for p in DST_HS.rglob('*.cc'):
    patch_file(p)
for p in DST_HS.rglob('*.h'):
    patch_file(p)

# ─── Generate CMakeLists.txt ─────────────────────────────────────────────────
cmake = """\
# CMakeLists.txt — hsaqmaodv NS-3 module
# Auto-generated by apply-hsaqmaodv-module.py

build_lib(
  LIBNAME hsaqmaodv
  SOURCE_FILES
    model/hsaqmaodv-rtable.cc
    model/hsaqmaodv-rqueue.cc
    model/hsaqmaodv-packet.cc
    model/hsaqmaodv-qtable.cc
    model/hsaqmaodv-routing-protocol.cc
    helper/hsaqmaodv-helper.cc
  HEADER_FILES
    model/hsaqmaodv-rtable.h
    model/hsaqmaodv-rqueue.h
    model/hsaqmaodv-packet.h
    model/hsaqmaodv-qtable.h
    model/hsaqmaodv-routing-protocol.h
    helper/hsaqmaodv-helper.h
  LIBRARIES_TO_LINK
    ${libcore}
    ${libnetwork}
    ${libinternet}
    ${libwifi}
    ${libenergy}
    ${libmobility}
    ${libsaqmaodv}
)
"""
(DST_HS / 'CMakeLists.txt').write_text(cmake)
info("  wrote CMakeLists.txt")

# ─── Add hsaqmaodv to top-level CMake if not present ─────────────────────────
cmake_lists = NS3_DIR / 'CMakeLists.txt'
token = 'add_subdirectory(src/hsaqmaodv)'
if cmake_lists.exists():
    content = cmake_lists.read_text()
    if 'src/hsaqmaodv' not in content:
        # Insert after saqmaodv line
        if 'src/saqmaodv' in content:
            content = content.replace(
                'add_subdirectory(src/saqmaodv)',
                'add_subdirectory(src/saqmaodv)\nadd_subdirectory(src/hsaqmaodv)'
            )
        else:
            content += f'\n{token}\n'
        cmake_lists.write_text(content)
        info("  patched top-level CMakeLists.txt")
    else:
        info("  CMakeLists.txt already contains hsaqmaodv")

print()
print("✓ hsaqmaodv module created at:", DST_HS)
print("  Next: run apply-hsaqmaodv-fanet.py to wire fanet-sim.cc")
